const DICT = {
  tr: {
    bossAttack: "Kurt saldırdı! Taşlar dondu ❄️", preTitle: "Güçlendirici seç", preSub: "Bölüme avantajlı başla", preBomb: "Bomba", preMoves: "+5 hamle", preAd: "Reklam izle: 💣", adFail: "Reklam şu an yok",
    tasks: "Görevler", tkDaily: "Günlük", tkWeekly: "Haftalık", tkAch: "Başarım", tkAlbum: "Albüm", tkResets: "Yenilenir:", tkChestHint: "Hepsini bitir, sandığı aç", tkOpen: "Sandığı aç", tkChestOpened: "Sandık açıldı! Yarın yenisi 🎉", tkMax: "Tamamlandı!", tkAlbumHint: "Kartlar sandıklardan düşer. Seriyi tamamla, 💎 kazan!", dShort: "g", hShort: "sa", mShort: "dk", tq_win: "{n} bölüm kazan", tq_stars: "{n} yıldız topla", tq_play: "{n} bölüm oyna", tq_harvest: "{n} kez hasat et", tq_plant: "{n} tarla ek", tq_collect: "{n} kez ürün topla", tq_order: "{n} sipariş teslim et", tq_booster: "{n} güçlendirici kullan", tq_sell: "Pazarda {n} ürün sat", tq_gift: "Arkadaşlara {n} hediye gönder", ach_win: "Galip", ach_stars: "Yıldız avcısı", ach_level: "Kaşif", ach_harvest: "Hasatçı", ach_order: "Tüccar", ach_help: "Yardımsever", ach_gift: "Cömert", set_animals: "Hayvanlar", set_crops: "Ürünler", set_themes: "Temalar",
    frWeekly: "Haftalık", frBox: "Günlük kutu", frBoxTomorrow: "Yarın yine", frCollect: "Topla", frAsksLife: "can istiyor", frSend: "Gönder", frSendLife: "Can gönder", frAskLife: "Can iste", frLifeSent: "❤ Can gönderildi!", frReqSent: "🙏 İstek gönderildi", frToday: "Bugün zaten yaptın, yarın tekrar", frWeekHint: "Bu hafta kazanılan yıldız", frChamp: "Geçen haftanın şampiyonu", you: "sen", dayShort: "g", hourShort: "sa", frHelp: "Yardım et", frHelped: "Yardım ettin! +🪙25 (arkadaşına +🪙40)", frHelpedToday: "Bugün bu çiftliğe yardım ettin",
    orders: "Sipariş panosu", deliver: "Teslim et", orderWait: "Yeni köylü geliyor", orderSkip: "Geç", farmLv: "Çiftlik sv.", ordersHint: "Ürünleri teslim et, 🪙 ve XP kazan. Seviye atlayınca 💎!",
    play: 'OYNA', chapter: 'Bölüm', hard: 'ZOR', hardLevel: 'ZOR SEVİYE', level: 'Seviye', moves: 'Hamle', score: 'Puan', goal: 'Hedef',
    win: 'Seviye Tamamlandı!', lose: 'Hamle Bitti', retry: 'Tekrar', next: 'Sonraki', map: 'Harita', farm: 'Çiftliğim', farmOwned: 'Senin! 🎉', farmNeeds: 'Önce gerekli', farmHave: 'sende', farmBuy: 'Satın al', collect: 'Topla', market: 'Pazar', nestEmpty: 'Kuluçka için yumurta topla.', nestReady: 'Civciv çıkmak üzere!', nestWins: 'bölüm kazan', hatch: 'Çıkar', incubate: 'Kuluçkaya koy', rush: 'Hızlandır', book: 'Koleksiyon', seasonOnly: 'Yalnız bu mevsim satışta!', questClaim: 'Al', questAll: 'Tüm görevler bitti! 🎉', questNext: 'Görev', plant: 'Ek', planted: 'ekildi', minShort: 'dk', cropTip: 'Her kazandığın bölüm ekinleri 5 dk hızlandırır!', cropFaster: 'Ekinler hızlandı',
    farmEarn: 'Yeterli yıldız yok. Seviye geç, yıldız kazan!',
    extraMoves: '+5 Hamle', watchAd: 'Reklam izle', buy: 'Satın al', coins: 'altın',
    noLives: 'Canın kalmadı', nextLife: 'Sonraki can', lifeAd: 'Reklam izle, 1 can kazan',
    friends: 'Arkadaşlar', frMyCode: 'Arkadaş kodun', frCopy: 'Kopyala', frAddHint: 'Arkadaş kodu ya da adı', frAdd: 'Ekle', frAdded: 'Arkadaş eklendi! 🎉', frEmpty: 'Henüz arkadaşın yok — kodunu paylaş!', frVisit: 'Ziyaret', frRemoveQ: 'arkadaşlıktan çıkarılsın mı?', frNotFound: 'Böyle bir oyuncu yok', frSelf: 'Kendini ekleyemezsin', frLimit: 'Arkadaş sınırına ulaştın', frBack: 'Geri', frVisiting: 'Ziyaret ediyorsun', frFarmErr: 'Çiftlik açılamadı',
    ranks: 'Sıralama', rkLevel: 'Bölüm', rkStars: 'Yıldız', rkSpent: 'Harcanan', rkWeek: 'Hafta', rkHint: 'Tüm zamanların en iyileri', rkSpentHint: 'Çiftliğe en çok yıldız harcayanlar', rkWeekHint: 'Bu hafta kazanılan yıldız (pazartesi sıfırlanır)', rkOffline: 'Bağlantı yok, sonra dene', rkEmpty: 'Henüz kimse yok — ilk sen ol!', rkYou: 'Senin sıran', rkNotYet: 'Listeye girmek için oynamaya devam et', rkGuest: 'Sıralamaya girmek için hesap aç — ilerlemen de bulutta saklanır.', shop: 'Mağaza', land: 'Arazi', landHint: 'Sağda ve solda satılık arsalar', plot: 'Arsa', plotBuy: 'Arsayı satın al', plotOwned: 'Senin arsan', needLevel: 'Seviye gerekli', preview: 'Önizle', close: 'Kapat', previewHint: 'Önizleme — beğendin mi?', expand: 'Genişlet', upgrade: 'Yükselt', needCoins: 'Yeterli altın yok', themes: 'Temalar', themeHint: 'Oyun ve harita görünümünü değiştir', owned: 'Sende', use: 'Kullan', needGems: 'Yeterli elmas yok', sellTab: 'Sat', tradeTab: 'Takas', tradeHint: 'Buğday, mısır ve ürünleri güçlendiriciye çevir', tradeNeed: 'Malzeme yetmiyor', ambarFull: 'Ambar dolu! Sat ya da yükselt', edit: 'Düzenle', editHint: 'Taşımak için bir yapıya dokun', done: 'Bitti', placeHint: 'Yerleştirmek için zemine dokun', place: 'Yerleştir', placeBad: 'Buraya sığmıyor', free: 'Bedava', removeAds: 'Reklamları kaldır', restore: 'Satın alımları geri yükle',
    daily: 'Günlük Ödül', claim: 'AL', day: 'Gün', streak: 'seri',
    hammer: 'Çekiç', moves5: '+5 Hamle', shuffle: 'Karıştır', prism: 'Prizma ile başla',
    objScore: 'puan topla', objCollect: 'topla', objJelly: 'jöleyi temizle', objRock: 'kayayı kır', objLock: 'zinciri kır',
    splashTag: 'Taşları eşle, çiftliğini büyüt', account: 'Hesap', accountHint: 'Giriş yap, ilerlemen her cihazda kalsın.', username: 'Kullanıcı adı', password: 'Şifre (en az 6)', login: 'Giriş yap', register: 'Yeni hesap aç', cancel: 'Vazgeç', guest: 'Hesapsız devam et', quitQ: 'Bölümden çıkılsın mı?', quitWarn: 'Çıkarsan 1 ❤ kaybedersin', quitYes: 'Çık (−1 ❤)', keepPlaying: 'Oynamaya devam', movesBonus: 'Kalan hamle', lifeSafe: 'Kazanırsan can gitmez ❤', logout: 'Çıkış yap', loggedAs: 'Giriş yapıldı:', saveCloud: 'Kaydet / Giriş yap', welcomeBack: 'Hoş geldin!', authErr_kullanici_adi: 'Kullanıcı adı 3-20 harf/rakam/_ olmalı', authErr_sifre_kisa: 'Şifre en az 6 karakter', authErr_alinmis: 'Bu kullanıcı adı alınmış', authErr_hatali: 'Kullanıcı adı veya şifre yanlış', authErr_ag: 'Bağlantı hatası, tekrar dene',
    tapToContinue: 'Devam etmek için dokun', settings: 'Ayarlar', profile: 'Profil', tapAvatar: 'Değiştirmek için avatara dokun', setName: 'Adını yaz', renameFarm: 'Çiftliğinin adı', saveBtn: 'Kaydet', codeHint: 'Kayıt kodu ile ilerlemeni başka cihaza taşıyabilirsin.', copyCode: 'Kayıt kodunu kopyala', loadCode: 'Kodla ilerleme yükle', copied: 'Kopyalandı!', badCode: 'Geçersiz kod', wipe: 'Hesabımı ve verilerimi sil', wipeConfirm: 'Tüm ilerlemen kalıcı olarak silinecek. Emin misin?', privacy: 'Gizlilik politikası', sound: 'Ses', lang: 'Dil',
    stars: 'yıldız', bonus: 'Kalan hamle bonusu', combo: 'KOMBO!', chain: 'Zincir', great: 'Harika!', amazing: 'Muhteşem!', legendary: 'Efsane!',
    tut1: 'Yan yana 3 mücevheri eşle', tut2: '4\'lü = Işın, L/T = Bomba, 5\'li = Prizma', tut3: 'İki özeli takas et: KOMBO',
    outOfMoves: 'Hamle kalmadı. Devam et?', continueFor: 'Devam et', notEnoughCoins: 'Yeterli altın yok',
    lives: 'Can', full: 'DOLU', farmStars: 'çiftlik yıldızı',
  },
  en: {
    bossAttack: "The wolf attacked! Gems froze ❄️", preTitle: "Pick a booster", preSub: "Start the level with an edge", preBomb: "Bomb", preMoves: "+5 moves", preAd: "Watch ad: 💣", adFail: "No ad right now",
    tasks: "Quests", tkDaily: "Daily", tkWeekly: "Weekly", tkAch: "Awards", tkAlbum: "Album", tkResets: "Resets in", tkChestHint: "Finish all, open the chest", tkOpen: "Open chest", tkChestOpened: "Chest opened! New one soon 🎉", tkMax: "Completed!", tkAlbumHint: "Cards drop from chests. Complete a set to earn 💎!", dShort: "d", hShort: "h", mShort: "m", tq_win: "Win {n} levels", tq_stars: "Collect {n} stars", tq_play: "Play {n} levels", tq_harvest: "Harvest {n} times", tq_plant: "Plant {n} plots", tq_collect: "Collect goods {n} times", tq_order: "Deliver {n} orders", tq_booster: "Use {n} boosters", tq_sell: "Sell {n} goods at market", tq_gift: "Send {n} gifts to friends", ach_win: "Champion", ach_stars: "Star hunter", ach_level: "Explorer", ach_harvest: "Harvester", ach_order: "Trader", ach_help: "Helper", ach_gift: "Generous", set_animals: "Animals", set_crops: "Crops", set_themes: "Themes",
    frWeekly: "Weekly", frBox: "Daily box", frBoxTomorrow: "Back tomorrow", frCollect: "Collect", frAsksLife: "asks for a life", frSend: "Send", frSendLife: "Send life", frAskLife: "Ask for life", frLifeSent: "❤ Life sent!", frReqSent: "🙏 Request sent", frToday: "Already done today, try tomorrow", frWeekHint: "Stars earned this week", frChamp: "Last week's champion", you: "you", dayShort: "d", hourShort: "h", frHelp: "Help", frHelped: "You helped! +🪙25 (friend gets +🪙40)", frHelpedToday: "You already helped this farm today",
    orders: "Order board", deliver: "Deliver", orderWait: "New villager coming", orderSkip: "Skip", farmLv: "Farm lv.", ordersHint: "Deliver goods for 🪙 and XP. Level up for 💎!",
    play: 'PLAY', chapter: 'Chapter', hard: 'HARD', hardLevel: 'HARD LEVEL', level: 'Level', moves: 'Moves', score: 'Score', goal: 'Goal',
    win: 'Level Complete!', lose: 'Out of Moves', retry: 'Retry', next: 'Next', map: 'Map', farm: 'My Farm', farmOwned: 'Yours! 🎉', farmNeeds: 'Requires', farmHave: 'you have', farmBuy: 'Buy', collect: 'Collect', market: 'Market', nestEmpty: 'Collect an egg to incubate.', nestReady: 'A chick is about to hatch!', nestWins: 'levels won', hatch: 'Hatch', incubate: 'Incubate', rush: 'Rush', book: 'Collection', seasonOnly: 'On sale this season only!', questClaim: 'Claim', questAll: 'All quests done! 🎉', questNext: 'Quest', plant: 'Plant', planted: 'planted', minShort: 'min', cropTip: 'Every level you win makes crops grow 5 min faster!', cropFaster: 'Crops sped up',
    farmEarn: 'Not enough stars. Beat levels to earn more!',
    extraMoves: '+5 Moves', watchAd: 'Watch ad', buy: 'Buy', coins: 'coins',
    noLives: 'No lives left', nextLife: 'Next life in', lifeAd: 'Watch ad, get 1 life',
    friends: 'Friends', frMyCode: 'Your friend code', frCopy: 'Copy', frAddHint: 'Friend code or name', frAdd: 'Add', frAdded: 'Friend added! 🎉', frEmpty: 'No friends yet — share your code!', frVisit: 'Visit', frRemoveQ: 'remove from friends?', frNotFound: 'No such player', frSelf: 'You cannot add yourself', frLimit: 'Friend limit reached', frBack: 'Back', frVisiting: 'Visiting', frFarmErr: 'Could not open the farm',
    ranks: 'Leaderboard', rkLevel: 'Level', rkStars: 'Stars', rkSpent: 'Spent', rkWeek: 'Week', rkHint: 'All-time best', rkSpentHint: 'Most stars spent on the farm', rkWeekHint: 'Stars earned this week (resets Monday)', rkOffline: 'No connection, try later', rkEmpty: 'Nobody yet — be the first!', rkYou: 'Your rank', rkNotYet: 'Keep playing to enter the list', rkGuest: 'Create an account to join the leaderboard — your progress is saved in the cloud too.', shop: 'Shop', land: 'Land', landHint: 'Plots for sale on the left and right', plot: 'Plot', plotBuy: 'Buy the plot', plotOwned: 'Your plot', needLevel: 'Level required', preview: 'Preview', close: 'Close', previewHint: 'Preview — like it?', expand: 'Expand', upgrade: 'Upgrade', needCoins: 'Not enough coins', themes: 'Themes', themeHint: 'Change the look of the game and map', owned: 'Owned', use: 'Use', needGems: 'Not enough gems', sellTab: 'Sell', tradeTab: 'Trade', tradeHint: 'Turn wheat, corn and goods into boosters', tradeNeed: 'Not enough goods', ambarFull: 'Barn full! Sell or upgrade', edit: 'Edit', editHint: 'Tap a building to move it', done: 'Done', placeHint: 'Tap the ground to place', place: 'Place', placeBad: 'Does not fit here', free: 'Free', removeAds: 'Remove ads', restore: 'Restore purchases',
    daily: 'Daily Reward', claim: 'CLAIM', day: 'Day', streak: 'streak',
    hammer: 'Hammer', moves5: '+5 Moves', shuffle: 'Shuffle', prism: 'Start with Prism',
    objScore: 'score', objCollect: 'collect', objJelly: 'clear jelly', objRock: 'break rocks', objLock: 'break chains',
    splashTag: 'Match gems, grow your farm', account: 'Account', accountHint: 'Sign in to keep your progress on every device.', username: 'Username', password: 'Password (min 6)', login: 'Sign in', register: 'Create account', cancel: 'Cancel', guest: 'Continue without account', quitQ: 'Quit the level?', quitWarn: 'Quitting costs 1 ❤', quitYes: 'Quit (−1 ❤)', keepPlaying: 'Keep playing', movesBonus: 'Moves left', lifeSafe: 'Win and keep your ❤', logout: 'Sign out', loggedAs: 'Signed in:', saveCloud: 'Save / Sign in', welcomeBack: 'Welcome back!', authErr_kullanici_adi: 'Username: 3-20 letters/digits/_', authErr_sifre_kisa: 'Password needs 6+ characters', authErr_alinmis: 'Username is taken', authErr_hatali: 'Wrong username or password', authErr_ag: 'Connection error, try again',
    tapToContinue: 'Tap to continue', settings: 'Settings', profile: 'Profile', tapAvatar: 'Tap the avatar to change it', setName: 'Enter your name', renameFarm: 'Name your farm', saveBtn: 'Save', codeHint: 'Use your save code to move progress to another device.', copyCode: 'Copy save code', loadCode: 'Load progress from code', copied: 'Copied!', badCode: 'Invalid code', wipe: 'Delete my account & data', wipeConfirm: 'All progress will be permanently deleted. Are you sure?', privacy: 'Privacy policy', sound: 'Sound', lang: 'Language',
    stars: 'stars', bonus: 'Leftover moves bonus', combo: 'COMBO!', chain: 'Chain', great: 'Great!', amazing: 'Amazing!', legendary: 'Legendary!',
    tut1: 'Match 3 gems in a row', tut2: '4 = Beam, L/T = Bomb, 5 = Prism', tut3: 'Swap two specials: COMBO',
    outOfMoves: 'Out of moves. Continue?', continueFor: 'Continue for', notEnoughCoins: 'Not enough coins',
    lives: 'Lives', full: 'FULL', farmStars: 'farm stars',
  },
};
let lang = 'en';
export function setLang(l) { lang = DICT[l] ? l : 'en'; }
export function getLang() { return lang; }
export function detectLang() {
  const n = (navigator.language || 'en').toLowerCase();
  return n.startsWith('tr') ? 'tr' : 'en';
}
export const t = (k) => DICT[lang][k] ?? DICT.en[k] ?? k;
